version: 2.1

executors:
  my-executor:
    working_directory: ~/hhsh
    docker:
      - image: ruby:2.6

commands:
  lint_check:
    steps:
      - checkout
      - run:
          name: lint_check
          command: |
            bundle install
            bundle exec rubocop

jobs:
  check:
    executor: my-executor
    steps:
      - lint_check


workflows:
  version: 2
  check:
    jobs:
      - check:
          # filters:
          #   branches:
          #     only:
          #       - master
